/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/project": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the active project overview */
    get: operations["getProject"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/issues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List open project issues */
    get: operations["listProjectIssues"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/issues/labels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List issue labels and their open-issue counts */
    get: operations["listIssueLabels"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/issues/{number}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one project issue */
    get: operations["getProjectIssue"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List approved directory members */
    get: operations["listMembers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/members/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a member by GitHub username
     * @description Approved members are public. A signed-in member may also read their own
     *     non-public profile; other non-public profiles return 404.
     */
    get: operations["getMemberByUsername"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/members/id/{githubId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a member by their numeric GitHub identifier */
    get: operations["getMemberByGithubId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the signed-in member's profile */
    get: operations["getCurrentProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update the signed-in member's profile
     * @description Only editable profile fields are accepted. Identity and moderation fields are rejected.
     */
    patch: operations["updateCurrentProfile"];
    trace?: never;
  };
  "/admin/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List members for moderation */
    get: operations["listAdminMembers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/members/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update a member's moderation status or priority */
    patch: operations["updateAdminMember"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    MemberStatus: "pending" | "approved" | "rejected" | "hidden";
    /** @enum {string} */
    Skill:
      | "engineering"
      | "ui-ux"
      | "qa"
      | "security"
      | "data"
      | "documentation"
      | "localization"
      | "research"
      | "community";
    IssueLabel: {
      name: string;
      color: string;
    };
    IssueLabelFacet: {
      name: string;
      count: number;
    };
    Issue: {
      number: number;
      title: string;
      body: string | null;
      /** @enum {string} */
      state: "open" | "closed";
      labels: components["schemas"]["IssueLabel"][];
      authorLogin: string;
      /** Format: uri */
      authorAvatarUrl: string | null;
      /** Format: uri */
      htmlUrl: string;
      commentsCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    IssueList: {
      issues: components["schemas"]["Issue"][];
      total: number;
      page: number;
      perPage: number;
    };
    Project: {
      /** Format: int64 */
      githubRepoId: number;
      fullName: string;
      title: string;
      description: string | null;
      /** Format: uri */
      htmlUrl: string;
      license: string | null;
      openIssueCount: number;
      memberCount: number;
      /** Format: date-time */
      lastSyncedAt: string | null;
    };
    Member: {
      /** Format: int64 */
      githubId: number;
      githubUsername: string;
      displayName: string;
      headline: string | null;
      affiliation: string | null;
      location: string | null;
      bio: string | null;
      links: string[];
      skills: components["schemas"]["Skill"][];
      /** @description Relative URL to the immutable avatar asset. */
      avatarUrl: string | null;
    };
    Profile: components["schemas"]["Member"] & {
      /** Format: uuid */
      id: string;
      status: components["schemas"]["MemberStatus"];
      /** Format: date-time */
      approvedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AdminMember: components["schemas"]["Profile"] & {
      priority: number;
      /** Format: uuid */
      approvedBy: string | null;
    };
    ProfileUpdate: {
      displayName?: string;
      headline?: string | null;
      affiliation?: string | null;
      location?: string | null;
      bio?: string | null;
      links?: string[];
      skills?: components["schemas"]["Skill"][];
    };
    AdminMemberUpdate: {
      status?: components["schemas"]["MemberStatus"];
      priority?: number;
    };
    ErrorDetail: {
      path: string;
      message: string;
    };
    Error: {
      /** @enum {string} */
      code:
        | "validation_error"
        | "unauthorized"
        | "forbidden"
        | "not_found"
        | "rate_limited"
        | "internal_error";
      message: string;
      details?: components["schemas"]["ErrorDetail"][];
    };
    ErrorResponse: {
      error: components["schemas"]["Error"];
    };
    ProjectResponse: {
      project: components["schemas"]["Project"];
    };
    IssueResponse: {
      issue: components["schemas"]["Issue"];
    };
    IssueLabelFacetListResponse: {
      labels: components["schemas"]["IssueLabelFacet"][];
    };
    MemberListResponse: {
      members: components["schemas"]["Member"][];
    };
    MemberResponse: {
      member: components["schemas"]["Member"];
    };
    ProfileResponse: {
      member: components["schemas"]["Profile"];
      isAdmin: boolean;
    };
    ProfileUpdateResponse: {
      member: components["schemas"]["Profile"];
    };
    AdminMemberListResponse: {
      members: components["schemas"]["AdminMember"][];
    };
    AdminMemberResponse: {
      member: components["schemas"]["AdminMember"];
    };
  };
  responses: {
    /** @description The request parameters or JSON body are invalid. */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Authentication is required. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description The authenticated actor is not permitted to perform this action. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description The requested resource does not exist or is not visible to the actor. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Too many requests from this client. */
    RateLimited: {
      headers: {
        /** @description Seconds until the client may retry. */
        "Retry-After": number;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description An unexpected server error. */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description GitHub login name. */
    GithubUsername: string;
    /** @description Numeric GitHub account identifier. */
    GithubId: number;
    /** @description Positive GitHub issue number. */
    IssueNumber: number;
    /** @description Internal member identifier, available to administrators only. */
    MemberId: string;
    /** @description Exact GitHub label name. */
    IssueLabel: string;
    /** @description Case-insensitive search of issue title and body. */
    IssueSearch: string;
    Page: number;
    PerPage: number;
    MemberStatus: components["schemas"]["MemberStatus"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active project overview. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  listProjectIssues: {
    parameters: {
      query?: {
        /** @description Exact GitHub label name. */
        label?: components["parameters"]["IssueLabel"];
        /** @description Case-insensitive search of issue title and body. */
        q?: components["parameters"]["IssueSearch"];
        page?: components["parameters"]["Page"];
        perPage?: components["parameters"]["PerPage"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of open issues, ordered by most recently updated first. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueList"];
        };
      };
      400: components["responses"]["ValidationError"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  listIssueLabels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Label facets for the active project. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueLabelFacetListResponse"];
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  getProjectIssue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Positive GitHub issue number. */
        number: components["parameters"]["IssueNumber"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The requested issue. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueResponse"];
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  listMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Approved members only, ordered by directory priority. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberListResponse"];
        };
      };
      500: components["responses"]["InternalError"];
    };
  };
  getMemberByUsername: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description GitHub login name. */
        username: components["parameters"]["GithubUsername"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The requested member profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberResponse"];
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  getMemberByGithubId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Numeric GitHub account identifier. */
        githubId: components["parameters"]["GithubId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The requested member profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberResponse"];
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  getCurrentProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The session member and their current administrative capability. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfileResponse"];
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalError"];
    };
  };
  updateCurrentProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileUpdate"];
      };
    };
    responses: {
      /** @description Updated self profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfileUpdateResponse"];
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  listAdminMembers: {
    parameters: {
      query?: {
        status?: components["parameters"]["MemberStatus"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Moderation queue, optionally filtered by status. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminMemberListResponse"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      500: components["responses"]["InternalError"];
    };
  };
  updateAdminMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Internal member identifier, available to administrators only. */
        id: components["parameters"]["MemberId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminMemberUpdate"];
      };
    };
    responses: {
      /** @description Updated moderation record. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminMemberResponse"];
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
}
